# Generated by Django 4.2 on 2025-10-16 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_attachment_actionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_meetings', to=settings.AUTH_USER_MODEL),
        ),
    ]
