# Generated by Django 4.2 on 2025-10-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_meeting_last_edited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='public_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('team', 'Team'), ('public', 'Public Link')], default='private', max_length=20),
        ),
    ]
